apply plugin: 'base'

subprojects {

    apply plugin: 'java'
    apply plugin: 'checkstyle'
    apply plugin: 'eclipse'
    apply plugin: 'maven-publish'

    java.toolchain.languageVersion = JavaLanguageVersion.of(8)

    repositories {
        mavenLocal()
        mavenCentral()
    }

    checkstyle {
        // The checkstyle version is derived from the maximum Java version we can use to build,
        // while maintaining compatibility with ForgeGradle for Minecraft 1.12.2 and the version is needs.
        toolVersion = "12.3.1"
    }

    dependencies {
        implementation 'org.jetbrains:annotations:24.0.0'

        testImplementation(platform("org.junit:junit-bom:5.9.2"))
        testImplementation("org.junit.jupiter:junit-jupiter:5.9.2")
    }

    tasks.test {
        useJUnitPlatform()
    }

}